package BasicEnums;

public enum ErrorType {
	NORMAL,
	CANNOT_FIND_CONFIGURATIONS_DATABSE,
	DATABASE_INITIALIZE_FAILED,
	DATABASE_CONNECT_FAILED,
	WRONG_CONFIGURATION_INFOS,
	WRONG_LOCAL_MACHINE_INFOS,
	COMMUNICATOR_SERVER_INITIALIZE_FAILED,
	COMMUNICATOR_SERVER_CREATE_CONNECTION_FAILED
}
