package BasicEnums;

public enum OperateType {

	IDLE,
	
	CHECK_SERVER,
	CHECK_INDEX,
	
	CHECK_DEPOT,
	CHECK_FOLDERS_FILES,
	
	OPEN_IN_SYSTEM,
	CREATE_FOLDER,
	CREATE_FILE,
	DELETE_FOLDER,
	DELETE_FILE,
	DELETE_CONTENT,
	COPY_FOLDER,
	COPY_FILE,
	RENAME_FOLDER,
	RENAME_FILE,
	MOVE_FOLDER,
	MOVE_FILE,
	RENAME_FOLDER_WITHOUT_EXTENSION,
	RENAME_FILE_WITHOUT_EXTENSION
}
